export const PLANS = {
  standard: {
    id: "standard",
    name: "STANDARD",
    headline: "Start Your Edge",
    price: 49,
    period: "month",
    billing: "Monthly billing",
    badge: null,
    features: [
      "Daily 2–4 VIP Signals",
      "Entry, Stop-Loss & Take-Profit — Every Trade",
      "Real-Time Telegram Alerts",
      "Live Modification & Closing Updates",
      "Full Education Library Access",
      "VIP Telegram Channel Delivery",
    ],
    cta: "START NOW — $49",
    href: "/payment/standard",
  },
  professional: {
    id: "professional",
    name: "PROFESSIONAL",
    headline: "Accelerate Returns",
    price: 99,
    period: "quarter",
    billing: "SAVE 33% — $33/month equivalent",
    badge: "MOST POPULAR",
    features: [
      "Daily 2–4 VIP Signals",
      "Entry, Stop-Loss & Take-Profit — Every Trade",
      "Real-Time Telegram Alerts",
      "Live Modification & Closing Updates",
      "Full Education Library Access",
      "VIP Telegram Channel Delivery",
      "Dedicated Support (24hr Response)",
    ],
    cta: "START NOW — $99",
    href: "/payment/professional",
  },
  elite: {
    id: "elite",
    name: "ELITE",
    headline: "Trade Like an Institution",
    price: 150,
    period: "year",
    billing: "SAVE 75% — $12.50/month equivalent",
    badge: "BEST VALUE",
    features: [
      "Daily 3–6 VIP Signals (Higher Frequency)",
      "Entry, Stop-Loss & Take-Profit — Every Trade",
      "Real-Time Telegram Alerts",
      "Live Modification & Closing Updates",
      "Full Education + Advanced Modules",
      "VIP Telegram Channel Delivery",
      "Priority Support (4hr Response)",
      "Monthly 1-on-1 Strategy Consultation",
    ],
    cta: "START NOW — $150",
    href: "/payment/elite",
  },
  permanent: {
    id: "permanent",
    name: "PERMANENT",
    headline: "Own Your Edge Forever",
    price: 209,
    period: "one-time",
    billing: "Never pay again. Ever.",
    badge: "LIFETIME ACCESS",
    features: [
      "Daily 3–6 VIP Signals — Forever",
      "Entry, Stop-Loss & Take-Profit — Every Trade",
      "Real-Time Telegram Alerts",
      "Live Modification & Closing Updates",
      "Lifetime Education Library Access",
      "VIP Telegram Channel Delivery",
      "Direct Line Support (WhatsApp/Telegram)",
      "All Future Updates & Features",
      "Lifetime Signal Access",
      "Personal Onboarding Session (30min call)",
    ],
    cta: "SECURE LIFETIME — $209",
    href: "/payment/permanent",
  },
};

export type PlanId = keyof typeof PLANS;
