export const PLANS = {
  standard: {
    id: "standard",
    name: "STANDARD",
    headline: "Start Your Edge",
    price: 49,
    period: "month",
    billing: "Monthly billing",
    features: [
      "Daily 2–4 VIP Signals",
      "Entry, Stop-Loss & Take-Profit — Every Trade",
      "Real-Time Telegram Alerts",
      "Live Modification & Closing Updates",
      "Full Education Library Access",
      "VIP Telegram Channel Delivery",
    ],
    cta: "SELECT — $49",
    href: "/payment/standard",
  },
  professional: {
    id: "professional",
    name: "PROFESSIONAL",
    headline: "Accelerate Returns",
    price: 99,
    period: "quarter",
    billing: "Quarterly billing — $33/month equivalent",
    features: [
      "All Standard features plus:",
      "Dedicated Support",
    ],
    cta: "SELECT — $99",
    href: "/payment/professional",
  },
  elite: {
    id: "elite",
    name: "ELITE",
    headline: "Trade Like an Institution",
    price: 150,
    period: "year",
    billing: "Annual billing — $12.50/month equivalent",
    features: [
      "All Professional features plus:",
      "Daily 3–6 VIP Signals (Higher Frequency)",
      "Priority Support",
    ],
    cta: "SELECT — $150",
    href: "/payment/elite",
  },
  permanent: {
    id: "permanent",
    name: "PERMANENT",
    headline: "Own Your Edge Forever",
    price: 209,
    period: "one-time",
    billing: "Single payment. Lifetime access.",
    features: [
      "All Elite features plus:",
      "Direct Line Support (WhatsApp/Telegram)",
      "All Future Updates & Features",
      "Lifetime Signal Access",
      "Personal Onboarding",
    ],
    cta: "SELECT — $209",
    href: "/payment/permanent",
  },
};

export type PlanId = keyof typeof PLANS;
